export enum Name {
  ChevronDown = 'chevron-down',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  ChevronUp = 'chevron-up',
  Close = 'close',
  Exit = 'exit',
  Facebook = 'facebook',
  FlagEn = 'flag-en',
  FlagLt = 'flag-lt',
  Globe = 'globe',
  Instagram = 'instagram',
  Kayak = 'kayak',
  Linkedin = 'linkedin',
  Path = 'path',
  Account = 'account',
  Twitter = 'twitter',
  User = 'user',
  Youtube = 'youtube',
}
