export interface Props extends React.SVGAttributes<SVGElement> {
  name: Name;
}

export enum Name {
  ChevronDown = 'chevron-down',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  ChevronUp = 'chevron-up',
  CircleCheck = 'circle-check',
  CirclePlus = 'circle-plus',
  CircleX = 'circle-x',
  Close = 'close',
  Exit = 'exit',
  Facebook = 'facebook',
  FileAvi = 'file-avi',
  FileBmp = 'file-bmp',
  FileDoc = 'file-doc',
  FileDocx = 'file-docx',
  FileGif = 'file-gif',
  FileJpg = 'file-jpg',
  FileMov = 'file-mov',
  FileMp3 = 'file-mp3',
  FileMp4 = 'file-mp4',
  FileMpg = 'file-mpg',
  FilePdf = 'file-pdf',
  FilePng = 'file-png',
  FileRar = 'file-rar',
  FileTxt = 'file-txt',
  FileWav = 'file-wav',
  FileXls = 'file-xls',
  FileXlsx = 'file-xlsx',
  FileZip = 'file-zip',
  File = 'file',
  FlagEn = 'flag-en',
  FlagLt = 'flag-lt',
  Globe = 'globe',
  Home = 'home',
  Info = 'info',
  Instagram = 'instagram',
  Kayak = 'kayak',
  Linkedin = 'linkedin',
  Lock = 'lock',
  Mail = 'mail',
  Path = 'path',
  Pencil = 'pencil',
  Phone = 'phone',
  Plus = 'plus',
  Trash = 'trash',
  Account = 'account',
  Twitter = 'twitter',
  User = 'user',
  Youtube = 'youtube',
}
